### ISSUE TITLE
Feature Suggestion: enable the possibility to share the tokens stack order

### ISSUE THREAD

**Issue by paulohdsc** [David-Zvekic/TokensVisible#11] opened 2021-06-22 21:35 UTC
There are situations where the position of tokens on the stack is relevant for combat or narrative purposes. In these cases, the GM may want to share the tokens Z axis order with the players. That's why I think it would be great if there was a (optional) way to propagate the z-index of tokens among everyone.

There is a module called ZSync that does this, but I tested it on versions 0.7.10 and 0.8.7 and it doesn't seem to work in conjunction with Your Tokens Visible.

Is there a way for your module to work in conjunction with ZSync, or to incorporate that module's functionality?

Thanks again!

**Comment by David-Zvekic** [comment] 2021-06-22 22:50
Based on what I see in the source code of ZSync, both these modules work
together as intended without conflict.

ZSync brings the clicked on token to the TOP of the stack for all
browsers, and sets all other tokens to a Zindex of 0 (making them equally
likely to be on the bottom).  The key is that you must control the token to
be allowed to click on it. But other than that it resets the Zindex for all
tokens to either 1 or 0.

'Your Tokens Visible' pushes the hovered-over token to the BOTTOM of your
local browser render stack, if you press 'z'.  It doesn't change the Zindex
of any token. It only changes the order in your own render stack.   It uses
hovering because the point of this feature is to remove tokens that are
obstructing your view (tokens you may not control and thus are not allowed
to click on). It moves them to the bottom of your local stack so anything
that was previously beneath it can be seen. It doesn't change the other
browsers. Players can cycle through whatever they are seeing without
affecting anyone except themself.

It isn't the intention of my module (or zsync apparently) to allow
controlling some kind of objective stack ordering.

Are you asking if I could make a method to push the hovered token backwards
AND synchronize it for every browser so someone can force a large token to
the back for all browsers?

**Comment by paulohdsc** [comment] 2021-06-23 23:45
Now with your explanation it's clear. I had forgotten that I must click on the token to get Zsync into action. My fault.

I think It's perfect that way. I can use Your Tokens Visible alone, to handle obstructing tokens, and I can click on a given token if I want to propagate its position to all users.

About what you said in the last paragraph, although that wasn't my initial question, I indeed think it would be really cool to have a feature that allows sending the selected token to the end of the stack and synchronize. It would be useful in many situations, like for vehicle tokens, for example. And if you're messing with that, you might consider incorporating ZSync functionality into your module as well, so it's a do-it-all module =)

But I'm actually satisfied with the answer so far. Thanks for your attention and for the module.

**Comment by David-Zvekic** [comment] 2021-08-16 03:08
I think the ability to control stack order needs to be in Zsync. its poor code cohesion to for 2 independant modules to both try to control this, one pushing backwards and sharing, and another pushing forwards and sharing.  I will leave Zsync to implement a sharable pushback if the author wants to. It makes sense in that module and its probably easier to implement.  The feature in YTV was deliberately intended to be a local only stack order as it frequently happens that 2 different players may disagree on which tokens they need to see at the top of the stack.

I'm closing this unless someone changes my mind about it.

**Closed as completed by David-Zvekic** 2021-08-16 03:08 UTC
